### ISSUE TITLE
[high-priority] using some variable names like 't' will invisibly and mysteriously give an error

### ISSUE THREAD

**Issue by pgbovine** [seankross/mario#33]
```
library(dplyr)
t <- tibble(number = c(1, 2, 3),
            letter = c("a", "b", "c"),
            greek = c("alpha", "beta", "gamma"))
t %>% select(letter)
```

gives this error: `"message": "Error in UseMethod(\"select\"): no applicable method for 'select' applied to an object of class \"function\"\n"`

```
library(dplyr)
t <- tibble(number = c(1, 2, 3),
            letter = c("a", "b", "c"),
            greek = c("alpha", "beta", "gamma"))
t %>% filter(number > 1)
```

gives a similar error: `"message": "Error in UseMethod(\"filter\"): no applicable method for 'filter' applied to an object of class \"function\"\n"`

**UPDATE: it turns out that the variable name 't' was the culprit here. If you change it to another name, it works. See below for more investigations.**

**Comment by pgbovine** [comment]
I just marked this as high-priority since it's important for users to be able to create their own small data sets from tibbles (or from a CSV file string) and do operations on it, to show small, self-contained examples

**Comment by pgbovine** [comment]
Related: this also doesn't work (but works if you just use data and don't convert it to a tibble):

```
data <- read.csv(text="flim,flam
+ 1.2,2.2
+ 77.1,3.14")
library(dplyr)
t <- as_tibble(data)
t %>% slice(1)
```

**Comment by pgbovine** [comment]
whoa whoa whoa something is really weird, i just found out that the variable name 't' seems to be the problem, not the tibble itself. this still breaks:

```
t <- read.csv(text="flim,flam
+ 1.2,2.2
+ 77.1,3.14")
t %>% slice(1)
```

... but this works:
```
not_t <- read.csv(text="flim,flam
+ 1.2,2.2
+ 77.1,3.14")
not_t %>% slice(1)
```

Going back to our original tibble examples, renaming it works:
```
library(dplyr)
not_t <- tibble(number = c(1, 2, 3),
            letter = c("a", "b", "c"),
            greek = c("alpha", "beta", "gamma"))
not_t %>% select(letter)
```

*OK this is a big issue since this is completely opaque to the user. This is high-priority to address.*

**Comment by pgbovine** [comment]
I haven't investigated myself, but I'm afraid if mario is somehow using variables like 't' in some way already then those creep into the user code's environment (much like how using filter and other dplyr functions in mario means they're automatically accessible by the user's code). In general, we need to more clearly separate out the user's code and mario's respective execution environments.

Also, not sure if this post is directly relevant, but i think we gotta do something about environments to more cleanly separate mario's and the user's code's environments:
https://stackoverflow.com/questions/39620669/source-script-to-separate-environment-in-r-not-the-global-environment

**Comment by seankross** [comment]
`t()` in R is used to transpose matrices and data frames. It is not used in mario, however it's one of the functions that is loaded automatically when you start R. These examples will cause the same error:

```r
"mean = mtcars; mean %>% select(cyl)" %>% mario::string_to_json()

"sum = mtcars; sum %>% select(cyl)" %>% mario::string_to_json()

"c = mtcars; c %>% select(cyl)" %>% mario::string_to_json()
```

In general overwriting built in function names with variables is a bad idea in R, and even if it doesn't cause problems in the mario execution environment it's bound to cause a problem somewhere else.

**Comment by pgbovine** [comment]
ah gotcha! good catch. but it does seem to work in R itself, right? even if it's a bad idea. i wonder what better warning message we can eventually give, since right now it's unclear to the user what's going on if they happen to accidentally use an r built-in. Is there some R linter we can run their code thru before calling mario?

```
> t <- read.csv(text="flim,flam
+ + 1.2,2.2
+ + 77.1,3.14")
> t %>% slice(1)
   flim flam
1 + 1.2  2.2
```

**Comment by pgbovine** [comment]
This is the error message:
```
      "message": "Error in UseMethod(\"select\"): no applicable method for 'select' applied to an object of class \"function\"\n"
```

In the interest of saving time, a super-hacky thing i could do now is to detect when the error message says `object of class "function"` or whatever and instead say "did you check that you didn't override a builtin R function?"

**Comment by pgbovine** [comment]
More generally, the eventual goal is to do something sensible no matter what the user inputs into mario:
- either it matches what R does
- or, if the behavior differs from what happens in R (as in the case of the 't' issue above), issue a clear warning message (e.g., "did you override an R builtin? try changing your variable names")

Pattern-matching hacks are totally OK to achieve this if it works most of the time :)

**Comment by pgbovine** [comment]
Example:
https://cran.r-project.org/web/packages/lintr/readme/README.html
