### ISSUE TITLE
group_by outline column in rhs instead of lhs [low priority]

### ISSUE THREAD

**Issue by pgbovine** [seankross/mario#37]
I can tweak this in my trace canonicalization script for now, so this is low-priority. but from some initial tests, it may be better to outline column(s) for group_by in rhs instead of lhs since rhs is where the groups show up (whereas lhs is an ungrouped table).

**Comment by pgbovine** [comment]
We agreed to do both lhs and rhs outlines for clarity

**Comment by seankross** [comment]
Should I change the trace output accordingly?

**Comment by pgbovine** [comment]
don't worry for now, i have it in my own canonicalization scripts already.

**Comment by pgbovine** [comment]
nevermind, i like leaving it lhs-only like you already have, since in rhs the groups are already clear
