### ISSUE TITLE
summarise by more than one value?

### ISSUE THREAD

**Issue by pgbovine** [seankross/mario#45]
not sure how important this is to support right now, but this came up in my archive of tests, and we currently don't support it. no worries if this is too much for now:

```r
# https://dplyr.tidyverse.org/reference/summarise.html
library(dplyr)

# dplyr 1.0.0 allows to summarise to more than one value:
mtcars %>%
   group_by(cyl) %>%
   summarise(qs = quantile(disp, c(0.25, 0.75)), prob = c(0.25, 0.75))
```

**Comment by seankross** [comment]
To update our mental models of the visualization: this means that multiple
arrows can start at a cell and multiple arrows can end at a cell.
Previously multiple arrows could only end at a cell. But this is the right
mental model and we should support this.
